export const prompts = [
    "Serene Mountain Lake",
    "Floating City in the Sky",
    "Timeless Ancient Ruins",
    "Whimsical Fairy Tale Cottage",
    "Vibrant Abstract Mosaic",
    "Tranquil Zen Garden",
    "Majestic Waterfall Cascade",
    "Celestial Nebula Formation",
    "Enigmatic Moonlit Forest",
    "Surreal Underwater Kingdom",
    "Galactic Symphony of Colors",
    "Mystical Starry Night Sky",
    "Enchanted Garden of Flowers",
    "Cosmic Journey through Wormholes",
    "Futuristic Hovering Vehicles",
    "Ancient Mythical Beasts",
    "Ethereal Ice Palace",
    "Abstract Geometric Patterns",
    "Steampunk Robot Army",
    "Dystopian Urban Decay",
    "Lush Tropical Paradise",
    "Energetic Burst of Light",
    "Whirling Spiral Galaxy",
    "Mind-Bending Optical Illusion",
    "Ancient Hieroglyphic Engravings",
    "Zen Mandala Art",
    "Digital Pixelated Dreamscape",
    "Enchanted Forest Creatures",
    "Sci-Fi Spaceship Armada",
    "Mesmerizing Kaleidoscope Symphony",
    "Intergalactic Space Exploration",
    "Rustic Countryside Farmstead",
    "Technicolor Geometric Architecture",
    "Dreamy Cloudscape",
    "Steampunk Time Machine",
    "Abstract Fluid Paint Swirls",
    "Celestial Alignment of Planets",
    "Urban City Skylines at Sunset",
    "Ancient Tribal Rituals",
    "Floating Islands in the Sky",
    "Neon Cyberpunk Streets",
    "Abstract Collage of Memories",
    "Futuristic Virtual Reality Experience",
    "Enigmatic Stonehenge-like Monuments",
    "Mystical Ancient Forest Guardians",
    "Cosmic Dance of Light and Shadows",
    "Otherworldly Alien Landscapes",
    "Whimsical Hot Air Balloon Adventure",
    "Psychedelic Pop Art Explosion",
    "Crystal Clear Underwater Caverns",
    "Abstract Energy Waves",
    "Medieval Castle on a Cliff",
    "Robot Companions in Everyday Life",
    "Imaginary Candy Land",
    "Techno-Organic Hybrid Creations",
    "Lost City in the Jungle",
    "Abstract Fractal Universe",
    "Futuristic Sports Arena",
    "Enchanted Watercolor Dreams",
    "Retro-Futuristic Steampunk City",
    "Mystical Shamanic Rituals",
    "Cosmic Collision of Galaxies",
    "Urban Street Art Extravaganza",
    "Crystaline Ice Cave Exploration",
    "Futuristic Bio-Mechanical Structures",
    "Whimsical Balloon Parade",
    "Abstract Fireworks Display",
    "Ancient Temples in the Mist",
    "Psychedelic Rainbow Landscape",
    "Robotic Insect Swarm",
    "Fantastical Carousel Ride",
    "Abstract Neon Light Installation",
    "Magical Book of Spells",
    "Futuristic Cyberspace Network",
    "Underwater Coral Garden",
    "Abstract Doodle Wonderland",
    "Futuristic Fashion Runway",
    "Ancient Sailing Ship on Stormy Seas",
    "Surreal Floating Head Sculptures",
    "Mystical Portal to Another World",
    "Galactic Battle of Spaceships",
    "Cybernetic Augmented Reality Experience",
    "Dreamy Moonlit Beach",
    "Technological City of Tomorrow",
    "Enigmatic Crop Circles in Fields",
    "Psychedelic Optical Art Illusions",
    "Mystical Ancient Runes and Symbols",
    "Abstract Particle Acceleration",
    "Steampunk Airship Fleet",
    "Whimsical Forest Tea Party",
    "Futuristic Robotic Architecture",
    "Celestial Symphony of Planets",
    "Mesmerizing Glitch Art",
    "Ancient Astronomical Observatories",
    "Colorful Abstract Glass Sculptures",
    "Retro Arcade Wonderland",
    "Mythical Phoenix Rising from Ashes",
    "Enchanted Glowing Fireflies in a Meadow",
    "Abstract Cybernetic Circuitry",
    "Magical Potion Creation in a Laboratory"
  ];
  
 
  